### ISSUE TITLE
python-documentcloud documentation webhooks broken

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/python-documentcloud#19]
One of the webhooks for python-documentcloud isn't working, fails to push new changes. (Changelog is stuck at 3.6.0) I don't have credentials to readthedocs to fix it.

**Comment by mitchelljkotler** [comment]
Can you create an account on readthedocs?  Then I can give you access to the account.

**Comment by duckduckgrayduck** [comment]
Created the new required yaml file:
https://blog.readthedocs.com/migrate-configuration-v2/
which fixed the webhook issue.
