### ISSUE TITLE
Test in multiple Python versions

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/python-documentcloud#20]
Current supported Python versions are 3.8 to 3.12, with 3.13 in prerelease: https://www.python.org/downloads/

This is also where we can test if Python 2 still works.

**Comment by duckduckgrayduck** [comment]
setup-python removed Python 2.7 back in June: 
https://github.com/actions/setup-python/issues/672
There is a workaround by using a container image, but we will want to discuss how much more workarounds we want to put into supporting Python 2 in the future at project planning. 

I did add all currently supported Python 3 versions into the matrix in this PR:
https://github.com/MuckRock/python-documentcloud/pull/21

**Comment by duckduckgrayduck** [comment]
3.6 is also not supported anymore. I added 3.7. The website needs to change to reflect these. Closing for now
